Select * from Accounts 
Select * from AccountTypes 
Select * from Users 
Select * from Customers 
Select * from Employees 
Select * from Branches 
Select * from Admins 
Select * from Transactions
Select * from TransactionTypes
select * from Loans
select * from LoanMasters